services:
    postgres:
      container_name: postgres-sql-um
      image: postgres
      environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 1152
          PGDATA: /var/lib/postgresql/data
          POSTGRES_DB: user-management
      volumes:
         - ./postgres:/data/postgres
      ports:
       - 5432:5432
      networks:
       - spring-demo
      restart: unless-stopped
    mail-dev:
       container_name: mail-dev-um
       image: maildev/maildev
       ports:
        - 1080:1080
        - 1025:1025
       networks:
         - spring-demo

    keycloak:
      container_name: keycloak-um
      image: quay.io/keycloak/keycloak:24.0.2
      ports:
        - 9090:8080
      environment:
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: admin
        JAVA_OPTS_APPEND: >-
          -Dcom.sun.mail.smtp.ssl.checkserveridentity=false
          -Dmail.smtp.ssl.trust=*
#        KC_MAIL_FROM: moncefhallab15@gmail.com
#        KC_MAIL_FROM_DISPLAY_NAME: Keycloak Admin
#        KC_MAIL_HOST: smtp.gmail.com
#        KC_MAIL_PORT: 465
#        KC_MAIL_USERNAME: moncefhallab15@gmail.com
#        KC_MAIL_PASSWORD: wqrn psxf efko nqff
#        KC_MAIL_SSL_ENABLED: true
#        KC_MAIL_STARTTLS_ENABLED: true
#        KC_MAIL_AUTH: true

      networks:
        - spring-demo
      command:
        - "start-dev"

networks:
   spring-demo:
      driver: bridge
   volumes:
   postgres:
      driver: local